openapi: 3.0.0
info:
  title: Zenzen API
  version: 1.0.0
  description: API for the Zenzen support system

paths:
  /api/templates:
    get:
      summary: List templates
      parameters:
        - name: type
          in: query
          schema:
            type: string
        - name: team_id
          in: query
          schema:
            type: string
            format: uuid
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: List of templates
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Template'
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                      pages:
                        type: integer
                      current_page:
                        type: integer
                      per_page:
                        type: integer
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
    post:
      summary: Create a template
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - type
                - content
              properties:
                title:
                  type: string
                type:
                  type: string
                content:
                  type: string
                team_id:
                  type: string
                  format: uuid
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Template created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Only administrators can create templates
        '500':
          description: Internal server error
    patch:
      summary: Update a template
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                team_id:
                  type: string
                  format: uuid
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Template updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Only administrators can update templates
        '500':
          description: Internal server error
    delete:
      summary: Delete a template
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Template deleted
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Only administrators can delete templates
        '500':
          description: Internal server error

components:
  schemas:
    Template:
      type: object
      required:
        - id
        - title
        - content
        - created_at
        - tags
      properties:
        id:
          type: string
          format: uuid
        created_by:
          type: string
          format: uuid
        title:
          type: string
        content:
          type: string
        created_at:
          type: string
          format: date-time
        team_id:
          type: string
          format: uuid
        tags:
          type: array
          items:
            type: string
        creator:
          type: object
          properties:
            name:
              type: string
              nullable: true
            email:
              type: string
        team:
          type: object
          properties:
            name:
              type: string
            focus_area:
              type: string
              nullable: true 